# Generated by Django 2.2 on 2022-04-18 11:23

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('img', models.ImageField(upload_to='product')),
                ('desc', models.TextField(max_length=500)),
                ('stock', models.IntegerField()),
            ],
        ),
    ]
